version: "3.9"
services:
  website:
    image: nginx:latest
    volumes:
      - ./nginx/html:/etc/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - "1883:1883"
      - "1884:1884"
    restart: always 